#ifndef _X_NOTIFY_EVENT_H__
#define _X_NOTIFY_EVENT_H__

typedef enum {
    XNOTIFY_EVENT_BUTTON_0,
    XNOTIFY_EVENT_BUTTON_1,
    XNOTIFY_EVENT_BUTTON_2,
    XNOTIFY_EVENT_BUTTON_3,
    XNOTIFY_EVENT_BUTTON_4,
    XNOTIFY_EVENT_INTR_0,
    XNOTIFY_EVENT_INTR_1,
    XNOTIFY_EVENT_INTR_2,
    XNOTIFY_EVENT_INTR_3,
    XNOTIFY_EVENT_INTR_4,
    XNOTIFY_EVENT_CABLE_0,
    XNOTIFY_EVENT_CABLE_1,
    XNOTIFY_EVENT_CABLE_2,
    XNOTIFY_EVENT_CABLE_3,
    XNOTIFY_EVENT_CABLE_4,
    XNOTIFY_EVENT_SWITCH_0,
    XNOTIFY_EVENT_SWITCH_1,
    XNOTIFY_EVENT_SWITCH_2,
    XNOTIFY_EVENT_SWITCH_3,
    XNOTIFY_EVENT_SWITCH_4,

    XNOTIFY_EVENT_MAX, // maximum value
} XNOTIFY_EVENT;

#endif //_X_NOTIFY_EVENT_H__
